spring:
  application:
    name: config
  cloud:
    config:
      server:
        native:
#          search-locations: {$CONFIG_PATH}
          search-locations: C:/StudyProjects/trade-app/config/src/main/resources/shared
  profiles:
    active: profile1
  name: config-server
server:
  port: 8890
management:
  endpoints:
    web:
      exposure:
        include: "shutdown"
  endpoint:
    shutdown:
      enabled: false
endpoints:
  shutdown:
    enabled: false