CREATE TABLE public.extsystem (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	alias varchar(10) NOT NULL,
	"name" varchar(100) NOT NULL
);
CREATE INDEX extsystem_id_idx ON public.extsystem (id);
COMMENT ON TABLE public.extsystem IS 'Extsystem table';

INSERT INTO "extsystem" ("alias", "name") VALUES ('yobit', 'yobit');
INSERT INTO "extsystem" ("alias", "name") VALUES ('bitmex', 'bitmex');