swagger: '2.0'
info:
  version: '1.0'
  title: Api Documentation
  description: Api Documentation
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0'
basePath: /datacollector
consumes:
  - application/json;charset=utf-8
produces:
  - application/json;charset=utf-8
paths:
  /init:
    post:
      tags:
        - datacollector
      summary: datacollector api
      operationId: fire
      consumes:
        - application/json
      parameters:
        - in: body
          name: initMsg
          description: init msg type
          required: true
          schema:
            $ref: '#/definitions/InitMessage'
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        default:
          description: Internal server error
      deprecated: false
definitions:
  InitMessage:
    description: >-
      Message payload contains information about platform (site) where we want grab data and crypto currency list
      that we want to calculate.
    type: object
    required:
      - extSystem
      - chain
    properties:
      extSystem:
        description: >-
          platform (site) name
        type: string
        example: null
      chain:
        description: >-
          crypto chain data list
        type: array
        items: string
        example: null
  InitChainMessage:
    description: >-
      Init chain message
    type: object
    required:
      - extSystemId
      - chain
      - chainElCount
    properties:
      messageId:
        description: >-
          Message id
        type: integer
        example: null
      extSystemId:
        description: >-
          ext system id
        type: integer
        example: null
      chain:
        description: >-
          crypto chain data list
        type: array
        items: number
        example: null
      chainElCount:
        description: >-
          Control check chain count
        type: integer
        example: null
  TradeCoupleMessage:
    description: >-
      Trade couple message
    type: object
    properties:
      messageId:
        description: >-
          Message id
        type: integer
        example: null
      chainId:
        description: >-
          Chain message id
        type: string
        example: null
      priorityId:
        description: >-
          Priority message id
        type: string
        example: null
      extSystemId:
        description: >-
          ext system id
        type: string
        example: null
      chain:
        description: >-
          crypto chain data list
        type: array
        items: string
        example: null
  TradeCouple:
    description: >-
      object contains:
        - ext system id
        - trade couple ids
        - buy rate
        - sell rate
        - buy currency count
        - sell currency count
    type: object
    properties:
      extSystemId:
          description: >-
            ext system id
          type: integer
      firstCurrencyID:
        description: >-
          first currecny internal id in couple
        type: integer
      secondCurrencyID:
        description: >-
          second currecny internal id in couple
        type: integer
      buyRate:
        description: >-
          buy rate
        type: number
      sellRate:
        description: >-
          sell rate
        type: number
      buyCount:
        description: >-
          currency buy count
        type: number
      sellCount:
        description: >-
          currency sell count
        type: number
  TradeCoupleReq:
    description: >-
      object contains:
        - trade couple ids
    type: object
    properties:
      firstCurrencyID:
        description: >-
          first currecny internal id in couple
        type: integer
      secondCurrencyID:
        description: >-
          second currecny internal id in couple
        type: integer